### PR TITLE
Cleaning all the invalid utf-8 chars params on email creation

### PR DESCRIPTION
**Pull request by kelvinst**
I'm getting some problems with invalid utf8 chars on other params.

This change makes sense for you?

### CODE REVIEW

**Comment by gabebw** [comment]
Can you add tests to ensure this doesn't happen again?

**Comment by gabebw** [comment]
It's hard for me to understand why this change makes sense (and prevent it happening again) without tests.

**Comment by kelvinst** [comment]
Oh, of course... :+1:

**Comment by kelvinst** [comment]
So intriguing. Looking a little to the tests, seems like the problem I'm getting (which driven me to this PR) was not meant to happen. I will investigate a little more and I keep you updated. Thank you.

**Comment by kelvinst** [comment]
Forget about this PR. I just misunderstood my own situation and all the code around it. :grin: 

I will open another PR with the "correct correction" for my problem.

**Pull request closed without merging**
