### PR TITLE
Allow postmark-griddler to access headers through the array it returns rather than a hash

### PR DESCRIPTION
**Pull request by seanscal**

### CODE REVIEW

**Comment by gabebw** [comment]
Can you add a test?

**Comment by gabebw** [comment]
Thanks! You can ignore the single/double quote warnings (we really gotta fix that :smile:), but the rest of Hound's recommendations are valid.

**Comment by wingrunr21** [comment]
@seanscal If you can fix Travis we can get this merged. I am slightly less concerned about Hound while I get caught up with PRs but feel free to fix whatever warnings you want.

**Comment by seanscal** [comment]
@wingrunr21 should be fixed

**Comment by wingrunr21** [comment]
Thanks, mind rebasing while you are at it?

**Comment by wingrunr21** [comment]
Note that I will be rebasing/merging these changes myself this weekend. Just an FYI if you care about how the commits look on GitHub.

**Comment by wingrunr21** [comment]
This has been rebased and merged.

**Pull request closed without merging**
