### PR TITLE
extract headers now cleaning non utf-8 chars

### PR DESCRIPTION
**Pull request by tmwangi**
Forked in MindSumo repo and fixed in that fork.

### CODE REVIEW

**Comment by superbilk** [comment]
+1 for merging.

added griddler to my project today and run into that utf problem within my first 5 testemails. very frustrating.

**Comment by gabebw** [comment]
Thanks! Merged as 8b0e6af264f10f75f8870985352625b5e3fbb162 and ce7558ab3b6bb12cebb78be8f4eb51e495f36305.

**Comment by gabebw** [comment]
I just released Griddler 1.1.1, which includes this change.

**Comment by tmwangi** [comment]
Thanks Gabe.

On 8 May 2015 at 13:06, Gabe Berke-Williams <notifications@github.com>
wrote:

> I just released Griddler 1.1.1, which includes this change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/griddler/pull/184#issuecomment-100344103>.
>



-- 
tim

**Pull request closed without merging**
