### PR TITLE
Extract controller methods into a concern for greater control

### PR DESCRIPTION
**Pull request by rzane**
Extracting the controller into a concern provides developers with more control. For example, with a module, I can control the inheritance chain. I can add `before_actions` without having to reopen the `EmailsController`.

This also keeps compatibility.

### CODE REVIEW

**Comment by wingrunr21** [comment]
I am not theoretically opposed, I'm just not clear how this solves your problem. You'd achieve the same result by subclassing `EmailsController`. Even with a concern, you still have to create your own controller, set your own routes, etc.

**Comment by rzane** [comment]
That's true. Subclassing would work in most cases. However, the specific case I'm concerned with is inheritance. By default, the `EmailsController` inherits from `ActionController::Base`.

**Comment by wingrunr21** [comment]
Ok I need more than that. While this does work for your use case (which I'm guessing is something like wanting to call the Griddler controller logic in something that subclasses, say, `ApplicationController`), I'm not seeing how it really "buys" the project anything. It is taking the controller-level logic inherent to the project and splitting it into two areas.

Also, in this instance, leaving the tests as-is isn't going to work. Moving the logic out to a concern means that concern needs to be unit tested. The controller we are shipping utilizing that concern then needs its tests updated appropriately. I'm going to insist on this as making this change effectively gives two points of consumption for the gem and each external point needs to be tested independently.

**Comment by rzane** [comment]
I'm not suggesting that I *can't* do without these changes, certainly, there are other ways to achieve my goals. However, I think it provides a more flexible API.

Re: tests. While I agree with your point about 'two points of consumption', I'm also not sure what I'd test that isn't covered by the original tests. All of the methods in the module are private. Since private methods are tested through their public interface, in my test, I would end up creating an anonymous controller with the exact implementation as the current `EmailsController` (because it's the simplest possible implementation).

**Comment by wingrunr21** [comment]
So I really do think subclassing the controller is a superior solution to this problem. However, I think your case + #255 presents a need for something more advanced than what is currently shipping. So, once we figure out the testing thing I'm ok merging this.

I understand that testing each independently seems trivial and redundant. However, it is entirely possible in the future that the "basic" controller and the concern will diverge in logic. Keeping the tests the same right now is convenient, but it does not reflect the new separation of concerns. Making sure `EmailsController` responds to `process_griddler` is probably sufficient to avoid regression provided the concern is fully tested.

Along the lines of a public interface, `process_griddler` should probably be public don't you think? That really is the public interface to that chunk of logic.

**Comment by rzane** [comment]
Okay, I see your point. I also agree that `process_griddler` should be public, but only so that it never changes. Since this is a controller, I think convention usually dictates that only actions should be public, so maybe `protected` would be best in this case.

**Comment by wingrunr21** [comment]
Sure, `protected` works

**Comment by rzane** [comment]
@wingrunr21 how're we looking?

**Pull request closed without merging**
