### PR TITLE
Deep clean invalid UTF8 bytes from headers hash

### PR DESCRIPTION
**Pull request by wouterw**
Fixes https://github.com/wingrunr21/griddler-mandrill/issues/18.

### CODE REVIEW

**Comment by holden** [comment]
+1

**Comment by smadeja** [comment]
+1

**Comment by resool** [comment]
+1

**Comment by arielvalentin** [comment]
+1

**Comment by gabebw** [comment]
Thanks! Just rebased and merged this as https://github.com/thoughtbot/griddler/commit/96336c3b431cd8ebb7b50ab8585844f858aae980.

**Pull request closed without merging**
