### PR TITLE
We must compile the CSS ourselves

### PR DESCRIPTION
**Pull request by gabebw**
Don't gitignore the CSS because GitHub pages won't auto-compile the SCSS to CSS for us. We have to do it ourselves.

Add the compiled CSS file back in.

### CODE REVIEW

**Comment by calebthompson** [comment]
Weird. I think they should do this now.

**Comment by calebthompson** [comment]
It works on my GH-pages site.

**Comment by gabebw** [comment]
Huh. http://griddler.io/ is totally blank right now and has no CSS.

**Comment by gabebw** [comment]
I didn't get any emails about failed builds.

**Comment by calebthompson** [comment]
Scroll down. You're right about main.css, though. It's 404ing.

**Comment by gabebw** [comment]
"scroll down" Oh hey it's right there! This CSS thing is silly.

**Comment by gabebw** [comment]
Typekit is also not found...

**Comment by gabebw** [comment]
Figured it out, I think: https://github.com/thoughtbot/griddler/pull/195

**Pull request closed without merging**
